services:
    akeep:
        image: node:22-alpine
        container_name: water-management
        restart: unless-stopped
        user: '1000'
        ports:
            - 5173:5173
            - 24678:24678
        env_file:
            - .env
        volumes:
            - ./:/app
            - ./public:/app/dist/public
        working_dir: /app
        command: sh -c "npm i && npm run nodemon"
        depends_on:
            - water-management_mongo

    water-management_mongo:
        image: mongodb/mongodb-community-server:latest
        container_name: water-management_mongo
        restart: unless-stopped
        ports:
            - '27017:27017'
        volumes:
            - mongodb:/data/db
        env_file:
            - ./.env

volumes:
    mongodb:
